/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LambdaDBError } from "./lambdadberror.js";

export type ResourceNotFoundErrorData = {
  message?: string | undefined;
};

export class ResourceNotFoundError extends LambdaDBError {
  /** The original data that was passed to this error instance. */
  data$: ResourceNotFoundErrorData;

  constructor(
    err: ResourceNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ResourceNotFoundError";
  }
}

/** @internal */
export const ResourceNotFoundError$inboundSchema: z.ZodType<
  ResourceNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ResourceNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ResourceNotFoundError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const ResourceNotFoundError$outboundSchema: z.ZodType<
  ResourceNotFoundError$Outbound,
  z.ZodTypeDef,
  ResourceNotFoundError
> = z.instanceof(ResourceNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceNotFoundError$ {
  /** @deprecated use `ResourceNotFoundError$inboundSchema` instead. */
  export const inboundSchema = ResourceNotFoundError$inboundSchema;
  /** @deprecated use `ResourceNotFoundError$outboundSchema` instead. */
  export const outboundSchema = ResourceNotFoundError$outboundSchema;
  /** @deprecated use `ResourceNotFoundError$Outbound` instead. */
  export type Outbound = ResourceNotFoundError$Outbound;
}
