/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { LambdaDBError } from "./lambdadberror.js";

export type ResourceNotFoundErrorData = {
  message?: string | undefined;
};

export class ResourceNotFoundError extends LambdaDBError {
  /** The original data that was passed to this error instance. */
  data$: ResourceNotFoundErrorData;

  constructor(
    err: ResourceNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ResourceNotFoundError";
  }
}

/** @internal */
export const ResourceNotFoundError$inboundSchema: z.ZodType<
  ResourceNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ResourceNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
