/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LambdaDBError } from "./lambdadberror.js";

export type ResourceAlreadyExistsErrorData = {
  message?: string | undefined;
};

export class ResourceAlreadyExistsError extends LambdaDBError {
  /** The original data that was passed to this error instance. */
  data$: ResourceAlreadyExistsErrorData;

  constructor(
    err: ResourceAlreadyExistsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "ResourceAlreadyExistsError";
  }
}

/** @internal */
export const ResourceAlreadyExistsError$inboundSchema: z.ZodType<
  ResourceAlreadyExistsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ResourceAlreadyExistsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ResourceAlreadyExistsError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const ResourceAlreadyExistsError$outboundSchema: z.ZodType<
  ResourceAlreadyExistsError$Outbound,
  z.ZodTypeDef,
  ResourceAlreadyExistsError
> = z.instanceof(ResourceAlreadyExistsError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResourceAlreadyExistsError$ {
  /** @deprecated use `ResourceAlreadyExistsError$inboundSchema` instead. */
  export const inboundSchema = ResourceAlreadyExistsError$inboundSchema;
  /** @deprecated use `ResourceAlreadyExistsError$outboundSchema` instead. */
  export const outboundSchema = ResourceAlreadyExistsError$outboundSchema;
  /** @deprecated use `ResourceAlreadyExistsError$Outbound` instead. */
  export type Outbound = ResourceAlreadyExistsError$Outbound;
}
