/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LambdaDbError } from "./lambdadberror.js";

export type TooManyRequestsErrorData = {
  message?: string | undefined;
};

export class TooManyRequestsError extends LambdaDbError {
  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "TooManyRequestsError";
  }
}

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodType<
  TooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type TooManyRequestsError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const TooManyRequestsError$outboundSchema: z.ZodType<
  TooManyRequestsError$Outbound,
  z.ZodTypeDef,
  TooManyRequestsError
> = z.instanceof(TooManyRequestsError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TooManyRequestsError$ {
  /** @deprecated use `TooManyRequestsError$inboundSchema` instead. */
  export const inboundSchema = TooManyRequestsError$inboundSchema;
  /** @deprecated use `TooManyRequestsError$outboundSchema` instead. */
  export const outboundSchema = TooManyRequestsError$outboundSchema;
  /** @deprecated use `TooManyRequestsError$Outbound` instead. */
  export type Outbound = TooManyRequestsError$Outbound;
}
