/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LambdaDBError } from "./lambdadberror.js";

export type UnauthenticatedErrorData = {
  message?: string | undefined;
};

export class UnauthenticatedError extends LambdaDBError {
  /** The original data that was passed to this error instance. */
  data$: UnauthenticatedErrorData;

  constructor(
    err: UnauthenticatedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "UnauthenticatedError";
  }
}

/** @internal */
export const UnauthenticatedError$inboundSchema: z.ZodType<
  UnauthenticatedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UnauthenticatedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UnauthenticatedError$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const UnauthenticatedError$outboundSchema: z.ZodType<
  UnauthenticatedError$Outbound,
  z.ZodTypeDef,
  UnauthenticatedError
> = z.instanceof(UnauthenticatedError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthenticatedError$ {
  /** @deprecated use `UnauthenticatedError$inboundSchema` instead. */
  export const inboundSchema = UnauthenticatedError$inboundSchema;
  /** @deprecated use `UnauthenticatedError$outboundSchema` instead. */
  export const outboundSchema = UnauthenticatedError$outboundSchema;
  /** @deprecated use `UnauthenticatedError$Outbound` instead. */
  export type Outbound = UnauthenticatedError$Outbound;
}
