/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsCreateCollection } from "../../funcs/collectionsCreateCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCollectionRequest$inboundSchema,
};

export const tool$collectionsCreateCollection: ToolDefinition<typeof args> = {
  name: "collections-create-collection",
  description: `Create a collection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsCreateCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
