/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsDocsDeleteDocs } from "../../funcs/collectionsDocsDeleteDocs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteDocsRequest$inboundSchema,
};

export const tool$collectionsDocsDeleteDocs: ToolDefinition<typeof args> = {
  name: "collections-docs-delete-docs",
  description:
    `Delete documents by document IDs or query filter from a collection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsDocsDeleteDocs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
