/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsQueryCollection } from "../../funcs/collectionsQueryCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.QueryCollectionRequest$inboundSchema,
};

export const tool$collectionsQueryCollection: ToolDefinition<typeof args> = {
  name: "collections-query-collection",
  description:
    `Search a collection with a query and return the most similar documents.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsQueryCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
