/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsDocsFetchDocs } from "../../funcs/collectionsDocsFetchDocs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchDocsRequest$inboundSchema,
};

export const tool$collectionsDocsFetchDocs: ToolDefinition<typeof args> = {
  name: "collections-docs-fetch-docs",
  description: `Lookup and return documents by document IDs from a collection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsDocsFetchDocs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
