/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsGetCollection } from "../../funcs/collectionsGetCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCollectionRequest$inboundSchema,
};

export const tool$collectionsGetCollection: ToolDefinition<typeof args> = {
  name: "collections-get-collection",
  description: `Get metadata of an existing collection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsGetCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
