/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsDocsUpsertDocs } from "../../funcs/collectionsDocsUpsertDocs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpsertDocsRequest$inboundSchema,
};

export const tool$collectionsDocsUpsertDocs: ToolDefinition<typeof args> = {
  name: "collections-docs-upsert-docs",
  description:
    `Upsert documents into a collection. Note that the maximum supported payload size is 6MB.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsDocsUpsertDocs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
