/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCollectionsDocsGetBulkUpsertDocs } from "../../funcs/projectsCollectionsDocsGetBulkUpsertDocs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBulkUpsertDocsRequest$inboundSchema,
};

export const tool$projectsCollectionsDocsGetBulkUpsertDocs: ToolDefinition<
  typeof args
> = {
  name: "projects-collections-docs-get-bulk-upsert-docs",
  description: `Request required info to upload documents.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsCollectionsDocsGetBulkUpsertDocs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
