/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCollectionsUpdateCollection } from "../../funcs/projectsCollectionsUpdateCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateCollectionRequest$inboundSchema,
};

export const tool$projectsCollectionsUpdateCollection: ToolDefinition<
  typeof args
> = {
  name: "projects-collections-update-collection",
  description: `Configure an collection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsCollectionsUpdateCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
