/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCollectionsDocsBulkUpsertDocs } from "../../funcs/projectsCollectionsDocsBulkUpsertDocs.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.BulkUpsertDocsRequest$inboundSchema,
};

export const tool$projectsCollectionsDocsBulkUpsertDocs: ToolDefinition<
  typeof args
> = {
  name: "projects-collections-docs-bulk-upsert-docs",
  description:
    `Bulk upsert documents into an collection. Note that the maximum supported object size is 200MB.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsCollectionsDocsBulkUpsertDocs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
