/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCollectionsQueryCollection } from "../../funcs/projectsCollectionsQueryCollection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.QueryCollectionRequest$inboundSchema,
};

export const tool$projectsCollectionsQueryCollection: ToolDefinition<
  typeof args
> = {
  name: "projects-collections-query-collection",
  description:
    `Search an collection with a query and return the most similar documents.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsCollectionsQueryCollection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
