/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsCreate } from "../funcs/collectionsCreate.js";
import { collectionsDelete } from "../funcs/collectionsDelete.js";
import { collectionsGet } from "../funcs/collectionsGet.js";
import { collectionsList } from "../funcs/collectionsList.js";
import { collectionsQuery } from "../funcs/collectionsQuery.js";
import { collectionsUpdate } from "../funcs/collectionsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Docs } from "./docs.js";

/**
 * @deprecated Use {@link LambdaDBClient} (e.g. `client.listCollections()`, `client.collection(name).get()`). This legacy API will be removed in a future major version.
 */
export class Collections extends ClientSDK {
  private _docs?: Docs;
  get docs(): Docs {
    return (this._docs ??= new Docs(this._options));
  }

  /**
   * List all collections in an existing project.
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.ListCollectionsResponse> {
    return unwrapAsync(collectionsList(
      this,
      options,
    ));
  }

  /**
   * Create a collection.
   */
  async create(
    request: operations.CreateCollectionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCollectionResponse> {
    return unwrapAsync(collectionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an existing collection.
   */
  async delete(
    request: operations.DeleteCollectionRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(collectionsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get metadata of an existing collection.
   */
  async get(
    request: operations.GetCollectionRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCollectionResponse> {
    return unwrapAsync(collectionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure a collection.
   */
  async update(
    request: operations.UpdateCollectionRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateCollectionResponse> {
    return unwrapAsync(collectionsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Search a collection with a query and return the most similar documents.
   */
  async query(
    request: operations.QueryCollectionRequest,
    options?: RequestOptions,
  ): Promise<operations.QueryCollectionResponse> {
    return unwrapAsync(collectionsQuery(
      this,
      request,
      options,
    ));
  }
}
