/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsDocsBulkUpsert } from "../funcs/collectionsDocsBulkUpsert.js";
import { collectionsDocsDelete } from "../funcs/collectionsDocsDelete.js";
import { collectionsDocsFetch } from "../funcs/collectionsDocsFetch.js";
import { collectionsDocsGetBulkUpsert } from "../funcs/collectionsDocsGetBulkUpsert.js";
import { collectionsDocsUpdate } from "../funcs/collectionsDocsUpdate.js";
import { collectionsDocsUpsert } from "../funcs/collectionsDocsUpsert.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Docs extends ClientSDK {
  /**
   * Upsert documents into a collection. Note that the maximum supported payload size is 6MB.
   */
  async upsert(
    request: operations.UpsertDocsRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(collectionsDocsUpsert(
      this,
      request,
      options,
    ));
  }

  /**
   * Request required info to upload documents.
   */
  async getBulkUpsert(
    request: operations.GetBulkUpsertDocsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetBulkUpsertDocsResponse> {
    return unwrapAsync(collectionsDocsGetBulkUpsert(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk upsert documents into a collection. Note that the maximum supported object size is 200MB.
   */
  async bulkUpsert(
    request: operations.BulkUpsertDocsRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(collectionsDocsBulkUpsert(
      this,
      request,
      options,
    ));
  }

  /**
   * Update documents in a collection. Note that the maximum supported payload size is 6MB.
   */
  async update(
    request: operations.UpdateDocsRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(collectionsDocsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete documents by document IDs or query filter from a collection.
   */
  async delete(
    request: operations.DeleteDocsRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(collectionsDocsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Lookup and return documents by document IDs from a collection.
   */
  async fetch(
    request: operations.FetchDocsRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchDocsResponse> {
    return unwrapAsync(collectionsDocsFetch(
      this,
      request,
      options,
    ));
  }
}
