/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Collections } from "./collections.js";

/**
 * @deprecated Use {@link LambdaDBClient} and `client.collection(name)` instead. This legacy client will be removed in a future major version.
 */
export class LambdaDB extends ClientSDK {
  private _collections?: Collections;
  get collections(): Collections {
    return (this._collections ??= new Collections(this._options));
  }
}
