/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @functional-systems/lambdadb SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx collectionsList.ts
 */

import { LambdaDB } from "@functional-systems/lambdadb";

const lambdaDB = new LambdaDB({
  projectApiKey: "<YOUR_PROJECT_API_KEY>",
});

async function main() {
  const result = await lambdaDB.list();

  console.log(result);
}

main().catch(console.error);
