/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type BulkUpsertDocsRequestBody = {
  /**
   * Object key uploaded based on bulk upsert info.
   */
  objectKey: string;
};

export type BulkUpsertDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: BulkUpsertDocsRequestBody;
};

/** @internal */
export type BulkUpsertDocsRequestBody$Outbound = {
  objectKey: string;
};

/** @internal */
export const BulkUpsertDocsRequestBody$outboundSchema: z.ZodType<
  BulkUpsertDocsRequestBody$Outbound,
  z.ZodTypeDef,
  BulkUpsertDocsRequestBody
> = z.object({
  objectKey: z.string(),
});

export function bulkUpsertDocsRequestBodyToJSON(
  bulkUpsertDocsRequestBody: BulkUpsertDocsRequestBody,
): string {
  return JSON.stringify(
    BulkUpsertDocsRequestBody$outboundSchema.parse(bulkUpsertDocsRequestBody),
  );
}

/** @internal */
export type BulkUpsertDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: BulkUpsertDocsRequestBody$Outbound;
};

/** @internal */
export const BulkUpsertDocsRequest$outboundSchema: z.ZodType<
  BulkUpsertDocsRequest$Outbound,
  z.ZodTypeDef,
  BulkUpsertDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => BulkUpsertDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function bulkUpsertDocsRequestToJSON(
  bulkUpsertDocsRequest: BulkUpsertDocsRequest,
): string {
  return JSON.stringify(
    BulkUpsertDocsRequest$outboundSchema.parse(bulkUpsertDocsRequest),
  );
}
