/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateCollectionRequest = {
  /**
   * Collection name must be unique within a project and the supported maximum length is 52.
   */
  collectionName: string;
  indexConfigs?: { [k: string]: models.IndexConfigsUnion } | undefined;
  partitionConfig?: models.PartitionConfig | undefined;
  sourceProjectName?: string | undefined;
  sourceCollectionName?: string | undefined;
  sourceDatetime?: string | undefined;
  sourceProjectApiKey?: string | undefined;
};

/**
 * Created collection
 */
export type CreateCollectionResponse = {
  collection: models.CollectionResponse;
};

/** @internal */
export type CreateCollectionRequest$Outbound = {
  collectionName: string;
  indexConfigs?: { [k: string]: models.IndexConfigsUnion$Outbound } | undefined;
  partitionConfig?: models.PartitionConfig$Outbound | undefined;
  sourceProjectName?: string | undefined;
  sourceCollectionName?: string | undefined;
  sourceDatetime?: string | undefined;
  sourceProjectApiKey?: string | undefined;
};

/** @internal */
export const CreateCollectionRequest$outboundSchema: z.ZodType<
  CreateCollectionRequest$Outbound,
  z.ZodTypeDef,
  CreateCollectionRequest
> = z.object({
  collectionName: z.string(),
  indexConfigs: z.record(models.IndexConfigsUnion$outboundSchema).optional(),
  partitionConfig: models.PartitionConfig$outboundSchema.optional(),
  sourceProjectName: z.string().optional(),
  sourceCollectionName: z.string().optional(),
  sourceDatetime: z.string().optional(),
  sourceProjectApiKey: z.string().optional(),
});

export function createCollectionRequestToJSON(
  createCollectionRequest: CreateCollectionRequest,
): string {
  return JSON.stringify(
    CreateCollectionRequest$outboundSchema.parse(createCollectionRequest),
  );
}

/** @internal */
export const CreateCollectionResponse$inboundSchema: z.ZodType<
  CreateCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: models.CollectionResponse$inboundSchema,
});

export function createCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCollectionResponse' from JSON`,
  );
}
