/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateCollectionRequest = {
  /**
   * Collection name must be unique within a project and the supported maximum length is 52.
   */
  collectionName: string;
  indexConfigs: { [k: string]: models.IndexConfigsUnion };
  description?: string | undefined;
  tags?: Record<string, string> | undefined;
  partitionConfig?: models.PartitionConfig | undefined;
  snapshotRetentionInDays?: number | undefined;
};

export type CreatedCollection = {
  collectionName: string;
  description: string;
  tags: Record<string, string>;
  defaultBranchName: "main";
  snapshotRetentionInDays: number;
  /** Collection creation time as Unix epoch milliseconds. */
  createdAt: number;
};

/**
 * Created collection
 */
export type CreateCollectionResponse = {
  collection: CreatedCollection;
};

/** @internal */
export type CreateCollectionRequest$Outbound = {
  collectionName: string;
  indexConfigs: { [k: string]: models.IndexConfigsUnion$Outbound };
  description?: string | undefined;
  tags?: Record<string, string> | undefined;
  partitionConfig?: models.PartitionConfig$Outbound | undefined;
  snapshotRetentionInDays?: number | undefined;
};

/** @internal */
export const CreateCollectionRequest$outboundSchema: z.ZodType<
  CreateCollectionRequest$Outbound,
  z.ZodTypeDef,
  CreateCollectionRequest
> = z.object({
  collectionName: z.string().regex(/^[a-zA-Z0-9_-]{3,52}$/),
  indexConfigs: z.record(models.IndexConfigsUnion$outboundSchema),
  description: z.string().max(255).optional(),
  tags: z.record(
    z.string().min(1).max(127).regex(/^[^:#,]+$/),
  ).refine((value) => Object.keys(value).length <= 5, {
    message: "Collection tags support at most five entries",
  }).refine(
    (value) => Object.keys(value).every((key) => /^[A-Za-z0-9_.-]{1,63}$/.test(key)),
    { message: "Invalid collection tag key" },
  ).optional(),
  partitionConfig: models.PartitionConfig$outboundSchema.optional(),
  snapshotRetentionInDays: z.number().int().min(1).max(31).optional(),
});

export function createCollectionRequestToJSON(
  createCollectionRequest: CreateCollectionRequest,
): string {
  return JSON.stringify(
    CreateCollectionRequest$outboundSchema.parse(createCollectionRequest),
  );
}

/** @internal */
export const CreateCollectionResponse$inboundSchema: z.ZodType<
  CreateCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.object({
    collectionName: z.string(),
    description: z.string(),
    tags: z.record(z.string()),
    defaultBranchName: z.literal("main"),
    snapshotRetentionInDays: z.number().int().min(1).max(31),
    createdAt: z.number().int(),
  }),
});

export function createCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateCollectionResponse' from JSON`,
  );
}
