/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DeleteDocsRequestBody = {
  /**
   * A list of document IDs.
   */
  ids?: Array<string> | undefined;
  /**
   * Query filter.
   */
  filter?: { [k: string]: any } | undefined;
  partitionFilter?: models.PartitionFilter | undefined;
};

export type DeleteDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: DeleteDocsRequestBody;
};

/** @internal */
export type DeleteDocsRequestBody$Outbound = {
  ids?: Array<string> | undefined;
  filter?: { [k: string]: any } | undefined;
  partitionFilter?: models.PartitionFilter$Outbound | undefined;
};

/** @internal */
export const DeleteDocsRequestBody$outboundSchema: z.ZodType<
  DeleteDocsRequestBody$Outbound,
  z.ZodTypeDef,
  DeleteDocsRequestBody
> = z.object({
  ids: z.array(z.string()).optional(),
  filter: z.record(z.any()).optional(),
  partitionFilter: models.PartitionFilter$outboundSchema.optional(),
});

export function deleteDocsRequestBodyToJSON(
  deleteDocsRequestBody: DeleteDocsRequestBody,
): string {
  return JSON.stringify(
    DeleteDocsRequestBody$outboundSchema.parse(deleteDocsRequestBody),
  );
}

/** @internal */
export type DeleteDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: DeleteDocsRequestBody$Outbound;
};

/** @internal */
export const DeleteDocsRequest$outboundSchema: z.ZodType<
  DeleteDocsRequest$Outbound,
  z.ZodTypeDef,
  DeleteDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => DeleteDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function deleteDocsRequestToJSON(
  deleteDocsRequest: DeleteDocsRequest,
): string {
  return JSON.stringify(
    DeleteDocsRequest$outboundSchema.parse(deleteDocsRequest),
  );
}
