/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteCollectionRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
};

/** @internal */
export type DeleteCollectionRequest$Outbound = {
  collectionName: string;
};

/** @internal */
export const DeleteCollectionRequest$outboundSchema: z.ZodType<
  DeleteCollectionRequest$Outbound,
  z.ZodTypeDef,
  DeleteCollectionRequest
> = z.object({
  collectionName: z.string(),
});

export function deleteCollectionRequestToJSON(
  deleteCollectionRequest: DeleteCollectionRequest,
): string {
  return JSON.stringify(
    DeleteCollectionRequest$outboundSchema.parse(deleteCollectionRequest),
  );
}
