/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteCollectionRequest = {
  /**
   * Project name.
   */
  projectName: string;
  /**
   * Collection name.
   */
  collectionName: string;
};

/**
 * Collection delete request accepted.
 */
export type DeleteCollectionResponse = {
  message?: string | undefined;
};

/** @internal */
export const DeleteCollectionRequest$inboundSchema: z.ZodType<
  DeleteCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
});

/** @internal */
export type DeleteCollectionRequest$Outbound = {
  projectName: string;
  collectionName: string;
};

/** @internal */
export const DeleteCollectionRequest$outboundSchema: z.ZodType<
  DeleteCollectionRequest$Outbound,
  z.ZodTypeDef,
  DeleteCollectionRequest
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCollectionRequest$ {
  /** @deprecated use `DeleteCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteCollectionRequest$inboundSchema;
  /** @deprecated use `DeleteCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteCollectionRequest$outboundSchema;
  /** @deprecated use `DeleteCollectionRequest$Outbound` instead. */
  export type Outbound = DeleteCollectionRequest$Outbound;
}

export function deleteCollectionRequestToJSON(
  deleteCollectionRequest: DeleteCollectionRequest,
): string {
  return JSON.stringify(
    DeleteCollectionRequest$outboundSchema.parse(deleteCollectionRequest),
  );
}

export function deleteCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCollectionRequest' from JSON`,
  );
}

/** @internal */
export const DeleteCollectionResponse$inboundSchema: z.ZodType<
  DeleteCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteCollectionResponse$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteCollectionResponse$outboundSchema: z.ZodType<
  DeleteCollectionResponse$Outbound,
  z.ZodTypeDef,
  DeleteCollectionResponse
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCollectionResponse$ {
  /** @deprecated use `DeleteCollectionResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteCollectionResponse$inboundSchema;
  /** @deprecated use `DeleteCollectionResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteCollectionResponse$outboundSchema;
  /** @deprecated use `DeleteCollectionResponse$Outbound` instead. */
  export type Outbound = DeleteCollectionResponse$Outbound;
}

export function deleteCollectionResponseToJSON(
  deleteCollectionResponse: DeleteCollectionResponse,
): string {
  return JSON.stringify(
    DeleteCollectionResponse$outboundSchema.parse(deleteCollectionResponse),
  );
}

export function deleteCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCollectionResponse' from JSON`,
  );
}
