/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type FetchDocsRequestBody = {
  /**
   * A list of document IDs to fetch. Note that the maximum number of document IDs is 100.
   */
  ids: Array<string>;
  /**
   * If your application requires a strongly consistent read, set consistentRead to true. Although a strongly consistent read might take more time than an eventually consistent read, it always returns the last updated value.
   */
  consistentRead?: boolean | undefined;
  /**
   * If your application need to include vector values in the response, set includeVectors to true.
   */
  includeVectors?: boolean | undefined;
  /**
   * An object to specify a list of field names to include and/or exclude in the result.
   */
  fields?: models.FieldsSelectorUnion | undefined;
  partitionFilter?: models.PartitionFilter | undefined;
};

export type FetchDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: FetchDocsRequestBody;
};

export type FetchDocsDoc = {
  collection: string;
  doc: { [k: string]: any };
};

/**
 * Fetched documents.
 */
export type FetchDocsResponse = {
  /**
   * Total number of documents returned.
   */
  total: number;
  /**
   * Elapsed time in milliseconds.
   */
  took: number;
  docs: Array<FetchDocsDoc>;
};

/** @internal */
export type FetchDocsRequestBody$Outbound = {
  ids: Array<string>;
  consistentRead: boolean;
  includeVectors: boolean;
  fields?: models.FieldsSelectorUnion$Outbound | undefined;
  partitionFilter?: models.PartitionFilter$Outbound | undefined;
};

/** @internal */
export const FetchDocsRequestBody$outboundSchema: z.ZodType<
  FetchDocsRequestBody$Outbound,
  z.ZodTypeDef,
  FetchDocsRequestBody
> = z.object({
  ids: z.array(z.string()),
  consistentRead: z.boolean().default(false),
  includeVectors: z.boolean().default(false),
  fields: models.FieldsSelectorUnion$outboundSchema.optional(),
  partitionFilter: models.PartitionFilter$outboundSchema.optional(),
});

export function fetchDocsRequestBodyToJSON(
  fetchDocsRequestBody: FetchDocsRequestBody,
): string {
  return JSON.stringify(
    FetchDocsRequestBody$outboundSchema.parse(fetchDocsRequestBody),
  );
}

/** @internal */
export type FetchDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: FetchDocsRequestBody$Outbound;
};

/** @internal */
export const FetchDocsRequest$outboundSchema: z.ZodType<
  FetchDocsRequest$Outbound,
  z.ZodTypeDef,
  FetchDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => FetchDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function fetchDocsRequestToJSON(
  fetchDocsRequest: FetchDocsRequest,
): string {
  return JSON.stringify(
    FetchDocsRequest$outboundSchema.parse(fetchDocsRequest),
  );
}

/** @internal */
export const FetchDocsDoc$inboundSchema: z.ZodType<
  FetchDocsDoc,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  doc: z.record(z.any()),
});

export function fetchDocsDocFromJSON(
  jsonString: string,
): SafeParseResult<FetchDocsDoc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchDocsDoc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchDocsDoc' from JSON`,
  );
}

/** @internal */
export const FetchDocsResponse$inboundSchema: z.ZodType<
  FetchDocsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int(),
  took: z.number().int(),
  docs: z.array(z.lazy(() => FetchDocsDoc$inboundSchema)),
});

export function fetchDocsResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchDocsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchDocsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchDocsResponse' from JSON`,
  );
}
