/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBulkUpsertDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
};

/**
 * Content type that must be specified when uploading documents.
 */
export const Type = {
  ApplicationJson: "application/json",
} as const;
/**
 * Content type that must be specified when uploading documents.
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * HTTP method that must be specified when uploading documents.
 */
export const HttpMethod = {
  Put: "PUT",
} as const;
/**
 * HTTP method that must be specified when uploading documents.
 */
export type HttpMethod = ClosedEnum<typeof HttpMethod>;

/**
 * Required info to upload documents.
 */
export type GetBulkUpsertDocsResponse = {
  /**
   * Presigned URL.
   */
  url: string;
  /**
   * Content type that must be specified when uploading documents.
   */
  type: Type;
  /**
   * HTTP method that must be specified when uploading documents.
   */
  httpMethod: HttpMethod;
  /**
   * Object key that must be specified when uploading documents.
   */
  objectKey: string;
  /**
   * Object size limit in bytes.
   */
  sizeLimitBytes: number;
};

/** @internal */
export type GetBulkUpsertDocsRequest$Outbound = {
  collectionName: string;
};

/** @internal */
export const GetBulkUpsertDocsRequest$outboundSchema: z.ZodType<
  GetBulkUpsertDocsRequest$Outbound,
  z.ZodTypeDef,
  GetBulkUpsertDocsRequest
> = z.object({
  collectionName: z.string(),
});

export function getBulkUpsertDocsRequestToJSON(
  getBulkUpsertDocsRequest: GetBulkUpsertDocsRequest,
): string {
  return JSON.stringify(
    GetBulkUpsertDocsRequest$outboundSchema.parse(getBulkUpsertDocsRequest),
  );
}

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const HttpMethod$inboundSchema: z.ZodNativeEnum<typeof HttpMethod> = z
  .nativeEnum(HttpMethod);

/** @internal */
export const GetBulkUpsertDocsResponse$inboundSchema: z.ZodType<
  GetBulkUpsertDocsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  type: Type$inboundSchema.default("application/json"),
  httpMethod: HttpMethod$inboundSchema.default("PUT"),
  objectKey: z.string(),
  sizeLimitBytes: z.number().int().default(209715200),
});

export function getBulkUpsertDocsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBulkUpsertDocsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBulkUpsertDocsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBulkUpsertDocsResponse' from JSON`,
  );
}
