/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetCollectionRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
};

/**
 * Describe collection success.
 */
export type GetCollectionResponse = {
  collection: models.CollectionResponse;
};

/** @internal */
export type GetCollectionRequest$Outbound = {
  collectionName: string;
};

/** @internal */
export const GetCollectionRequest$outboundSchema: z.ZodType<
  GetCollectionRequest$Outbound,
  z.ZodTypeDef,
  GetCollectionRequest
> = z.object({
  collectionName: z.string(),
});

export function getCollectionRequestToJSON(
  getCollectionRequest: GetCollectionRequest,
): string {
  return JSON.stringify(
    GetCollectionRequest$outboundSchema.parse(getCollectionRequest),
  );
}

/** @internal */
export const GetCollectionResponse$inboundSchema: z.ZodType<
  GetCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: models.CollectionResponse$inboundSchema,
});

export function getCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCollectionResponse' from JSON`,
  );
}
