/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  /**
   * Max number of documents to return at once.
   */
  size?: number | undefined;
  /**
   * Next page token.
   */
  pageToken?: string | undefined;
};

/**
 * Documents list.
 */
export type ListDocsResponse = {
  total: number;
  /**
   * A list of documents.
   */
  docs: Array<{ [k: string]: any }>;
  nextPageToken?: string | undefined;
};

/** @internal */
export type ListDocsRequest$Outbound = {
  collectionName: string;
  size?: number | undefined;
  pageToken?: string | undefined;
};

/** @internal */
export const ListDocsRequest$outboundSchema: z.ZodType<
  ListDocsRequest$Outbound,
  z.ZodTypeDef,
  ListDocsRequest
> = z.object({
  collectionName: z.string(),
  size: z.number().int().optional(),
  pageToken: z.string().optional(),
});

export function listDocsRequestToJSON(
  listDocsRequest: ListDocsRequest,
): string {
  return JSON.stringify(ListDocsRequest$outboundSchema.parse(listDocsRequest));
}

/** @internal */
export const ListDocsResponse$inboundSchema: z.ZodType<
  ListDocsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int(),
  docs: z.array(z.record(z.any())),
  nextPageToken: z.string().optional(),
});

export function listDocsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocsResponse' from JSON`,
  );
}
