/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { nullToUndefined, safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  /**
   * Max number of documents to return at once.
   */
  size?: number | undefined;
  /**
   * Next page token.
   */
  pageToken?: string | undefined;
  /**
   * Set to true to include vector values in the response. Defaults to false.
   */
  includeVectors?: boolean | undefined;
  /** Read ref kind. Must be supplied together with refName. */
  refKind?: models.ReadRef["kind"] | undefined;
  /** Read ref name. Must be supplied together with refKind. */
  refName?: string | undefined;
};

export type ListDocsDoc = {
  collection: string;
  doc: { [k: string]: any };
};

/**
 * Documents list.
 */
export type ListDocsResponse = {
  total: number;
  /**
   * A list of documents.
   */
  docs: Array<ListDocsDoc>;
  nextPageToken?: string | undefined;
  /**
   * Whether the list of documents is included.
   */
  isDocsInline: boolean;
  /**
   * Download URL for the list of documents.
   */
  docsUrl?: string | undefined;
};

/** @internal */
export type ListDocsRequest$Outbound = {
  collectionName: string;
  size?: number | undefined;
  pageToken?: string | undefined;
  includeVectors: boolean;
  refKind?: models.ReadRef["kind"] | undefined;
  refName?: string | undefined;
};

/** @internal */
export const ListDocsRequest$outboundSchema: z.ZodType<
  ListDocsRequest$Outbound,
  z.ZodTypeDef,
  ListDocsRequest
> = z.object({
  collectionName: z.string(),
  size: z.number().int().optional(),
  pageToken: z.string().optional(),
  includeVectors: z.boolean().default(false),
  refKind: z.enum(["branch", "tag", "alias"]).optional(),
  refName: z.string().regex(/^[a-zA-Z0-9_-]{3,52}$/).optional(),
}).superRefine((value, context) => {
  if ((value.refKind == null) !== (value.refName == null)) {
    context.addIssue({
      code: z.ZodIssueCode.custom,
      message: "refKind and refName must be supplied together",
      path: [value.refKind == null ? "refKind" : "refName"],
    });
  }
});

export function listDocsRequestToJSON(
  listDocsRequest: ListDocsRequest,
): string {
  return JSON.stringify(ListDocsRequest$outboundSchema.parse(listDocsRequest));
}

export type ListDocsExtendedRequestBody = {
  /**
   * Max number of documents to return at once.
   */
  size?: number | undefined;
  /**
   * Next page token.
   */
  pageToken?: string | undefined;
  /**
   * Filter applied before pagination.
   */
  filter?: { [k: string]: any } | undefined;
  partitionFilter?: models.PartitionFilter | undefined;
  /**
   * An object to specify a list of field names to include and/or exclude in the result.
   */
  fields?: models.FieldsSelectorUnion | undefined;
  /**
   * Set to true to include vector values in the response. Defaults to false.
   */
  includeVectors?: boolean | undefined;
  /** Read target. Omitting it reads from main. */
  ref?: models.ReadRef | undefined;
};

export type ListDocsExtendedRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: ListDocsExtendedRequestBody;
};

/** @internal */
export type ListDocsExtendedRequestBody$Outbound = {
  size?: number | undefined;
  pageToken?: string | undefined;
  filter?: { [k: string]: any } | undefined;
  partitionFilter?: models.PartitionFilter$Outbound | undefined;
  fields?: models.FieldsSelectorUnion$Outbound | undefined;
  includeVectors: boolean;
  ref?: models.ReadRef | undefined;
};

/** @internal */
export const ListDocsExtendedRequestBody$outboundSchema: z.ZodType<
  ListDocsExtendedRequestBody$Outbound,
  z.ZodTypeDef,
  ListDocsExtendedRequestBody
> = z.object({
  size: z.number().int().optional(),
  pageToken: z.string().optional(),
  filter: z.record(z.any()).optional(),
  partitionFilter: models.PartitionFilter$outboundSchema.optional(),
  fields: models.FieldsSelectorUnion$outboundSchema.optional(),
  includeVectors: z.boolean().default(false),
  ref: models.ReadRef$schema.optional(),
});

export function listDocsExtendedRequestBodyToJSON(
  listDocsExtendedRequestBody: ListDocsExtendedRequestBody,
): string {
  return JSON.stringify(
    ListDocsExtendedRequestBody$outboundSchema.parse(listDocsExtendedRequestBody),
  );
}

/** @internal */
export type ListDocsExtendedRequest$Outbound = {
  collectionName: string;
  RequestBody: ListDocsExtendedRequestBody$Outbound;
};

/** @internal */
export const ListDocsExtendedRequest$outboundSchema: z.ZodType<
  ListDocsExtendedRequest$Outbound,
  z.ZodTypeDef,
  ListDocsExtendedRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => ListDocsExtendedRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function listDocsExtendedRequestToJSON(
  listDocsExtendedRequest: ListDocsExtendedRequest,
): string {
  return JSON.stringify(
    ListDocsExtendedRequest$outboundSchema.parse(listDocsExtendedRequest),
  );
}

/** @internal */
export const ListDocsDoc$inboundSchema: z.ZodType<
  ListDocsDoc,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string(),
  doc: z.record(z.any()),
});

/** @internal */
export const ListDocsResponse$inboundSchema: z.ZodType<
  ListDocsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int(),
  docs: z.array(ListDocsDoc$inboundSchema),
  nextPageToken: nullToUndefined(z.string().optional()),
  isDocsInline: z.boolean(),
  docsUrl: nullToUndefined(z.string().optional()),
});

export function listDocsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocsResponse' from JSON`,
  );
}
