/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * A list of collections matched with a projectName.
 */
export type ListCollectionsResponse = {
  collections: Array<models.CollectionResponse>;
};

/** @internal */
export const ListCollectionsResponse$inboundSchema: z.ZodType<
  ListCollectionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collections: z.array(models.CollectionResponse$inboundSchema),
});

export function listCollectionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCollectionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCollectionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCollectionsResponse' from JSON`,
  );
}
