/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Query object.
 */
export type Query = {};

export type Sort = {};

export type QueryCollectionRequestBody = {
  /**
   * Number of documents to return. Note that the maximum number of documents is 1000.
   */
  size: number;
  /**
   * Query object.
   */
  query?: Query | undefined;
  /**
   * If your application requires a strongly consistent read, set consistentRead to true. Although a strongly consistent read might take more time than an eventually consistent read, it always returns the last updated value.
   */
  consistentRead?: boolean | undefined;
  /**
   * If your application need to include vector values in the response, set includeVectors to true.
   */
  includeVectors?: boolean | undefined;
  /**
   * List of field name, sort direction pairs.
   */
  sort?: Array<Sort> | undefined;
  /**
   * List of field name to include in results
   */
  fields?: Array<string> | undefined;
};

export type QueryCollectionRequest = {
  /**
   * Project name.
   */
  projectName: string;
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: QueryCollectionRequestBody;
};

export type QueryCollectionDocDoc = {};

export type QueryCollectionDoc = {
  /**
   * Collection name.
   */
  collection?: string | undefined;
  /**
   * Document similarity score.
   */
  score?: number | undefined;
  doc?: QueryCollectionDocDoc | undefined;
};

/**
 * Documents selected by query.
 */
export type QueryCollectionResponse = {
  /**
   * Elapsed time in milliseconds.
   */
  took?: number | undefined;
  /**
   * Maximum score.
   */
  maxScore?: number | undefined;
  /**
   * Total number of documents returned.
   */
  total?: number | undefined;
  /**
   * List of documents.
   */
  docs?: Array<QueryCollectionDoc> | undefined;
};

/** @internal */
export const Query$inboundSchema: z.ZodType<Query, z.ZodTypeDef, unknown> = z
  .object({});

/** @internal */
export type Query$Outbound = {};

/** @internal */
export const Query$outboundSchema: z.ZodType<
  Query$Outbound,
  z.ZodTypeDef,
  Query
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Query$ {
  /** @deprecated use `Query$inboundSchema` instead. */
  export const inboundSchema = Query$inboundSchema;
  /** @deprecated use `Query$outboundSchema` instead. */
  export const outboundSchema = Query$outboundSchema;
  /** @deprecated use `Query$Outbound` instead. */
  export type Outbound = Query$Outbound;
}

export function queryToJSON(query: Query): string {
  return JSON.stringify(Query$outboundSchema.parse(query));
}

export function queryFromJSON(
  jsonString: string,
): SafeParseResult<Query, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Query$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Query' from JSON`,
  );
}

/** @internal */
export const Sort$inboundSchema: z.ZodType<Sort, z.ZodTypeDef, unknown> = z
  .object({});

/** @internal */
export type Sort$Outbound = {};

/** @internal */
export const Sort$outboundSchema: z.ZodType<Sort$Outbound, z.ZodTypeDef, Sort> =
  z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Sort$ {
  /** @deprecated use `Sort$inboundSchema` instead. */
  export const inboundSchema = Sort$inboundSchema;
  /** @deprecated use `Sort$outboundSchema` instead. */
  export const outboundSchema = Sort$outboundSchema;
  /** @deprecated use `Sort$Outbound` instead. */
  export type Outbound = Sort$Outbound;
}

export function sortToJSON(sort: Sort): string {
  return JSON.stringify(Sort$outboundSchema.parse(sort));
}

export function sortFromJSON(
  jsonString: string,
): SafeParseResult<Sort, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sort$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sort' from JSON`,
  );
}

/** @internal */
export const QueryCollectionRequestBody$inboundSchema: z.ZodType<
  QueryCollectionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  size: z.number().int(),
  query: z.lazy(() => Query$inboundSchema).optional(),
  consistentRead: z.boolean().default(false),
  includeVectors: z.boolean().default(false),
  sort: z.array(z.lazy(() => Sort$inboundSchema)).optional(),
  fields: z.array(z.string()).optional(),
});

/** @internal */
export type QueryCollectionRequestBody$Outbound = {
  size: number;
  query?: Query$Outbound | undefined;
  consistentRead: boolean;
  includeVectors: boolean;
  sort?: Array<Sort$Outbound> | undefined;
  fields?: Array<string> | undefined;
};

/** @internal */
export const QueryCollectionRequestBody$outboundSchema: z.ZodType<
  QueryCollectionRequestBody$Outbound,
  z.ZodTypeDef,
  QueryCollectionRequestBody
> = z.object({
  size: z.number().int(),
  query: z.lazy(() => Query$outboundSchema).optional(),
  consistentRead: z.boolean().default(false),
  includeVectors: z.boolean().default(false),
  sort: z.array(z.lazy(() => Sort$outboundSchema)).optional(),
  fields: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryCollectionRequestBody$ {
  /** @deprecated use `QueryCollectionRequestBody$inboundSchema` instead. */
  export const inboundSchema = QueryCollectionRequestBody$inboundSchema;
  /** @deprecated use `QueryCollectionRequestBody$outboundSchema` instead. */
  export const outboundSchema = QueryCollectionRequestBody$outboundSchema;
  /** @deprecated use `QueryCollectionRequestBody$Outbound` instead. */
  export type Outbound = QueryCollectionRequestBody$Outbound;
}

export function queryCollectionRequestBodyToJSON(
  queryCollectionRequestBody: QueryCollectionRequestBody,
): string {
  return JSON.stringify(
    QueryCollectionRequestBody$outboundSchema.parse(queryCollectionRequestBody),
  );
}

export function queryCollectionRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueryCollectionRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCollectionRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCollectionRequestBody' from JSON`,
  );
}

/** @internal */
export const QueryCollectionRequest$inboundSchema: z.ZodType<
  QueryCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  RequestBody: z.lazy(() => QueryCollectionRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type QueryCollectionRequest$Outbound = {
  projectName: string;
  collectionName: string;
  RequestBody: QueryCollectionRequestBody$Outbound;
};

/** @internal */
export const QueryCollectionRequest$outboundSchema: z.ZodType<
  QueryCollectionRequest$Outbound,
  z.ZodTypeDef,
  QueryCollectionRequest
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  requestBody: z.lazy(() => QueryCollectionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryCollectionRequest$ {
  /** @deprecated use `QueryCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = QueryCollectionRequest$inboundSchema;
  /** @deprecated use `QueryCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = QueryCollectionRequest$outboundSchema;
  /** @deprecated use `QueryCollectionRequest$Outbound` instead. */
  export type Outbound = QueryCollectionRequest$Outbound;
}

export function queryCollectionRequestToJSON(
  queryCollectionRequest: QueryCollectionRequest,
): string {
  return JSON.stringify(
    QueryCollectionRequest$outboundSchema.parse(queryCollectionRequest),
  );
}

export function queryCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<QueryCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCollectionRequest' from JSON`,
  );
}

/** @internal */
export const QueryCollectionDocDoc$inboundSchema: z.ZodType<
  QueryCollectionDocDoc,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type QueryCollectionDocDoc$Outbound = {};

/** @internal */
export const QueryCollectionDocDoc$outboundSchema: z.ZodType<
  QueryCollectionDocDoc$Outbound,
  z.ZodTypeDef,
  QueryCollectionDocDoc
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryCollectionDocDoc$ {
  /** @deprecated use `QueryCollectionDocDoc$inboundSchema` instead. */
  export const inboundSchema = QueryCollectionDocDoc$inboundSchema;
  /** @deprecated use `QueryCollectionDocDoc$outboundSchema` instead. */
  export const outboundSchema = QueryCollectionDocDoc$outboundSchema;
  /** @deprecated use `QueryCollectionDocDoc$Outbound` instead. */
  export type Outbound = QueryCollectionDocDoc$Outbound;
}

export function queryCollectionDocDocToJSON(
  queryCollectionDocDoc: QueryCollectionDocDoc,
): string {
  return JSON.stringify(
    QueryCollectionDocDoc$outboundSchema.parse(queryCollectionDocDoc),
  );
}

export function queryCollectionDocDocFromJSON(
  jsonString: string,
): SafeParseResult<QueryCollectionDocDoc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCollectionDocDoc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCollectionDocDoc' from JSON`,
  );
}

/** @internal */
export const QueryCollectionDoc$inboundSchema: z.ZodType<
  QueryCollectionDoc,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: z.string().optional(),
  score: z.number().optional(),
  doc: z.lazy(() => QueryCollectionDocDoc$inboundSchema).optional(),
});

/** @internal */
export type QueryCollectionDoc$Outbound = {
  collection?: string | undefined;
  score?: number | undefined;
  doc?: QueryCollectionDocDoc$Outbound | undefined;
};

/** @internal */
export const QueryCollectionDoc$outboundSchema: z.ZodType<
  QueryCollectionDoc$Outbound,
  z.ZodTypeDef,
  QueryCollectionDoc
> = z.object({
  collection: z.string().optional(),
  score: z.number().optional(),
  doc: z.lazy(() => QueryCollectionDocDoc$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryCollectionDoc$ {
  /** @deprecated use `QueryCollectionDoc$inboundSchema` instead. */
  export const inboundSchema = QueryCollectionDoc$inboundSchema;
  /** @deprecated use `QueryCollectionDoc$outboundSchema` instead. */
  export const outboundSchema = QueryCollectionDoc$outboundSchema;
  /** @deprecated use `QueryCollectionDoc$Outbound` instead. */
  export type Outbound = QueryCollectionDoc$Outbound;
}

export function queryCollectionDocToJSON(
  queryCollectionDoc: QueryCollectionDoc,
): string {
  return JSON.stringify(
    QueryCollectionDoc$outboundSchema.parse(queryCollectionDoc),
  );
}

export function queryCollectionDocFromJSON(
  jsonString: string,
): SafeParseResult<QueryCollectionDoc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCollectionDoc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCollectionDoc' from JSON`,
  );
}

/** @internal */
export const QueryCollectionResponse$inboundSchema: z.ZodType<
  QueryCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  took: z.number().int().optional(),
  maxScore: z.number().optional(),
  total: z.number().int().optional(),
  docs: z.array(z.lazy(() => QueryCollectionDoc$inboundSchema)).optional(),
});

/** @internal */
export type QueryCollectionResponse$Outbound = {
  took?: number | undefined;
  maxScore?: number | undefined;
  total?: number | undefined;
  docs?: Array<QueryCollectionDoc$Outbound> | undefined;
};

/** @internal */
export const QueryCollectionResponse$outboundSchema: z.ZodType<
  QueryCollectionResponse$Outbound,
  z.ZodTypeDef,
  QueryCollectionResponse
> = z.object({
  took: z.number().int().optional(),
  maxScore: z.number().optional(),
  total: z.number().int().optional(),
  docs: z.array(z.lazy(() => QueryCollectionDoc$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryCollectionResponse$ {
  /** @deprecated use `QueryCollectionResponse$inboundSchema` instead. */
  export const inboundSchema = QueryCollectionResponse$inboundSchema;
  /** @deprecated use `QueryCollectionResponse$outboundSchema` instead. */
  export const outboundSchema = QueryCollectionResponse$outboundSchema;
  /** @deprecated use `QueryCollectionResponse$Outbound` instead. */
  export type Outbound = QueryCollectionResponse$Outbound;
}

export function queryCollectionResponseToJSON(
  queryCollectionResponse: QueryCollectionResponse,
): string {
  return JSON.stringify(
    QueryCollectionResponse$outboundSchema.parse(queryCollectionResponse),
  );
}

export function queryCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCollectionResponse' from JSON`,
  );
}
