/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { collectionTagsSchema } from "../../lib/collectionContract.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

type UpdateCollectionFields = {
  indexConfigs?: { [k: string]: models.IndexConfigsUnion } | null | undefined;
  description?: string | null | undefined;
  tags?: Record<string, string> | null | undefined;
  snapshotRetentionInDays?: number | null | undefined;
};

export type UpdateCollectionRequestBody =
  | (UpdateCollectionFields & {
    indexConfigs: { [k: string]: models.IndexConfigsUnion };
  })
  | (UpdateCollectionFields & { description: string })
  | (UpdateCollectionFields & { tags: Record<string, string> })
  | (UpdateCollectionFields & { snapshotRetentionInDays: number });

export type UpdateCollectionRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpdateCollectionRequestBody;
};

/**
 * Updated collection
 */
export type UpdateCollectionResponse = {
  collection: models.CollectionResponse;
};

/** @internal */
type UpdateCollectionFields$Outbound = {
  indexConfigs?:
    | { [k: string]: models.IndexConfigsUnion$Outbound }
    | null
    | undefined;
  description?: string | null | undefined;
  tags?: Record<string, string> | null | undefined;
  snapshotRetentionInDays?: number | null | undefined;
};

export type UpdateCollectionRequestBody$Outbound =
  | (UpdateCollectionFields$Outbound & {
    indexConfigs: { [k: string]: models.IndexConfigsUnion$Outbound };
  })
  | (UpdateCollectionFields$Outbound & { description: string })
  | (UpdateCollectionFields$Outbound & { tags: Record<string, string> })
  | (UpdateCollectionFields$Outbound & { snapshotRetentionInDays: number });

/** @internal */
export const UpdateCollectionRequestBody$outboundSchema: z.ZodType<
  UpdateCollectionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateCollectionRequestBody
> = z.object({
  indexConfigs: z.record(models.IndexConfigsUnion$outboundSchema).refine(
    (value) => Object.keys(value).length > 0,
    { message: "Collection indexConfigs must contain at least one field" },
  ).nullable().optional(),
  description: z.string().max(255).nullable().optional(),
  tags: collectionTagsSchema.nullable().optional(),
  snapshotRetentionInDays: z.number().int().min(1).max(31).nullable().optional(),
}).strict().refine(
  (value) => Object.values(value).some((item) => item !== undefined && item !== null),
  { message: "At least one non-null collection field must be provided" },
) as z.ZodType<
  UpdateCollectionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateCollectionRequestBody
>;

export function updateCollectionRequestBodyToJSON(
  updateCollectionRequestBody: UpdateCollectionRequestBody,
): string {
  return JSON.stringify(
    UpdateCollectionRequestBody$outboundSchema.parse(
      updateCollectionRequestBody,
    ),
  );
}

/** @internal */
export type UpdateCollectionRequest$Outbound = {
  collectionName: string;
  RequestBody: UpdateCollectionRequestBody$Outbound;
};

/** @internal */
export const UpdateCollectionRequest$outboundSchema: z.ZodType<
  UpdateCollectionRequest$Outbound,
  z.ZodTypeDef,
  UpdateCollectionRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => UpdateCollectionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateCollectionRequestToJSON(
  updateCollectionRequest: UpdateCollectionRequest,
): string {
  return JSON.stringify(
    UpdateCollectionRequest$outboundSchema.parse(updateCollectionRequest),
  );
}

/** @internal */
export const UpdateCollectionResponse$inboundSchema: z.ZodType<
  UpdateCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: models.CollectionResponse$inboundSchema,
});

export function updateCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCollectionResponse' from JSON`,
  );
}
