/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateDocsRequestBody = {
  /**
   * A list of documents to update. Each document must contain 'id' field to be updated.
   */
  docs: Array<{ [k: string]: any }>;
};

export type UpdateDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpdateDocsRequestBody;
};

/** @internal */
export type UpdateDocsRequestBody$Outbound = {
  docs: Array<{ [k: string]: any }>;
};

/** @internal */
export const UpdateDocsRequestBody$outboundSchema: z.ZodType<
  UpdateDocsRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateDocsRequestBody
> = z.object({
  docs: z.array(z.record(z.any())),
});

export function updateDocsRequestBodyToJSON(
  updateDocsRequestBody: UpdateDocsRequestBody,
): string {
  return JSON.stringify(
    UpdateDocsRequestBody$outboundSchema.parse(updateDocsRequestBody),
  );
}

/** @internal */
export type UpdateDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: UpdateDocsRequestBody$Outbound;
};

/** @internal */
export const UpdateDocsRequest$outboundSchema: z.ZodType<
  UpdateDocsRequest$Outbound,
  z.ZodTypeDef,
  UpdateDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => UpdateDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateDocsRequestToJSON(
  updateDocsRequest: UpdateDocsRequest,
): string {
  return JSON.stringify(
    UpdateDocsRequest$outboundSchema.parse(updateDocsRequest),
  );
}
