/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateDocsDoc = {};

export type UpdateDocsRequestBody = {
  /**
   * A list of documents to update. Each document must contain 'id' field to be updated.
   */
  docs: Array<UpdateDocsDoc>;
};

export type UpdateDocsRequest = {
  /**
   * Project name.
   */
  projectName: string;
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpdateDocsRequestBody;
};

/**
 * Update request accepted.
 */
export type UpdateDocsResponse = {
  message?: string | undefined;
};

/** @internal */
export const UpdateDocsDoc$inboundSchema: z.ZodType<
  UpdateDocsDoc,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type UpdateDocsDoc$Outbound = {};

/** @internal */
export const UpdateDocsDoc$outboundSchema: z.ZodType<
  UpdateDocsDoc$Outbound,
  z.ZodTypeDef,
  UpdateDocsDoc
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDocsDoc$ {
  /** @deprecated use `UpdateDocsDoc$inboundSchema` instead. */
  export const inboundSchema = UpdateDocsDoc$inboundSchema;
  /** @deprecated use `UpdateDocsDoc$outboundSchema` instead. */
  export const outboundSchema = UpdateDocsDoc$outboundSchema;
  /** @deprecated use `UpdateDocsDoc$Outbound` instead. */
  export type Outbound = UpdateDocsDoc$Outbound;
}

export function updateDocsDocToJSON(updateDocsDoc: UpdateDocsDoc): string {
  return JSON.stringify(UpdateDocsDoc$outboundSchema.parse(updateDocsDoc));
}

export function updateDocsDocFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocsDoc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocsDoc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocsDoc' from JSON`,
  );
}

/** @internal */
export const UpdateDocsRequestBody$inboundSchema: z.ZodType<
  UpdateDocsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  docs: z.array(z.lazy(() => UpdateDocsDoc$inboundSchema)),
});

/** @internal */
export type UpdateDocsRequestBody$Outbound = {
  docs: Array<UpdateDocsDoc$Outbound>;
};

/** @internal */
export const UpdateDocsRequestBody$outboundSchema: z.ZodType<
  UpdateDocsRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateDocsRequestBody
> = z.object({
  docs: z.array(z.lazy(() => UpdateDocsDoc$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDocsRequestBody$ {
  /** @deprecated use `UpdateDocsRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateDocsRequestBody$inboundSchema;
  /** @deprecated use `UpdateDocsRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateDocsRequestBody$outboundSchema;
  /** @deprecated use `UpdateDocsRequestBody$Outbound` instead. */
  export type Outbound = UpdateDocsRequestBody$Outbound;
}

export function updateDocsRequestBodyToJSON(
  updateDocsRequestBody: UpdateDocsRequestBody,
): string {
  return JSON.stringify(
    UpdateDocsRequestBody$outboundSchema.parse(updateDocsRequestBody),
  );
}

export function updateDocsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocsRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateDocsRequest$inboundSchema: z.ZodType<
  UpdateDocsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  RequestBody: z.lazy(() => UpdateDocsRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateDocsRequest$Outbound = {
  projectName: string;
  collectionName: string;
  RequestBody: UpdateDocsRequestBody$Outbound;
};

/** @internal */
export const UpdateDocsRequest$outboundSchema: z.ZodType<
  UpdateDocsRequest$Outbound,
  z.ZodTypeDef,
  UpdateDocsRequest
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  requestBody: z.lazy(() => UpdateDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDocsRequest$ {
  /** @deprecated use `UpdateDocsRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateDocsRequest$inboundSchema;
  /** @deprecated use `UpdateDocsRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateDocsRequest$outboundSchema;
  /** @deprecated use `UpdateDocsRequest$Outbound` instead. */
  export type Outbound = UpdateDocsRequest$Outbound;
}

export function updateDocsRequestToJSON(
  updateDocsRequest: UpdateDocsRequest,
): string {
  return JSON.stringify(
    UpdateDocsRequest$outboundSchema.parse(updateDocsRequest),
  );
}

export function updateDocsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocsRequest' from JSON`,
  );
}

/** @internal */
export const UpdateDocsResponse$inboundSchema: z.ZodType<
  UpdateDocsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type UpdateDocsResponse$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const UpdateDocsResponse$outboundSchema: z.ZodType<
  UpdateDocsResponse$Outbound,
  z.ZodTypeDef,
  UpdateDocsResponse
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDocsResponse$ {
  /** @deprecated use `UpdateDocsResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateDocsResponse$inboundSchema;
  /** @deprecated use `UpdateDocsResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateDocsResponse$outboundSchema;
  /** @deprecated use `UpdateDocsResponse$Outbound` instead. */
  export type Outbound = UpdateDocsResponse$Outbound;
}

export function updateDocsResponseToJSON(
  updateDocsResponse: UpdateDocsResponse,
): string {
  return JSON.stringify(
    UpdateDocsResponse$outboundSchema.parse(updateDocsResponse),
  );
}

export function updateDocsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocsResponse' from JSON`,
  );
}
