/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateCollectionRequestBody = {
  indexConfigs?: { [k: string]: models.IndexConfigsUnion } | undefined;
  description?: string | undefined;
  tags?: Record<string, string> | undefined;
  snapshotRetentionInDays?: number | undefined;
};

export type UpdateCollectionRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpdateCollectionRequestBody;
};

/**
 * Updated collection
 */
export type UpdateCollectionResponse = {
  collection: models.CollectionResponse;
};

/** @internal */
export type UpdateCollectionRequestBody$Outbound = {
  indexConfigs?: { [k: string]: models.IndexConfigsUnion$Outbound } | undefined;
  description?: string | undefined;
  tags?: Record<string, string> | undefined;
  snapshotRetentionInDays?: number | undefined;
};

/** @internal */
export const UpdateCollectionRequestBody$outboundSchema: z.ZodType<
  UpdateCollectionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateCollectionRequestBody
> = z.object({
  indexConfigs: z.record(models.IndexConfigsUnion$outboundSchema).optional(),
  description: z.string().max(255).optional(),
  tags: z.record(
    z.string().min(1).max(127).regex(/^[^:#,]+$/),
  ).refine((value) => Object.keys(value).length <= 5, {
    message: "Collection tags support at most five entries",
  }).refine(
    (value) => Object.keys(value).every((key) => /^[A-Za-z0-9_.-]{1,63}$/.test(key)),
    { message: "Invalid collection tag key" },
  ).optional(),
  snapshotRetentionInDays: z.number().int().min(1).max(31).optional(),
}).refine((value) => Object.values(value).some((item) => item !== undefined), {
  message: "At least one collection field must be provided",
});

export function updateCollectionRequestBodyToJSON(
  updateCollectionRequestBody: UpdateCollectionRequestBody,
): string {
  return JSON.stringify(
    UpdateCollectionRequestBody$outboundSchema.parse(
      updateCollectionRequestBody,
    ),
  );
}

/** @internal */
export type UpdateCollectionRequest$Outbound = {
  collectionName: string;
  RequestBody: UpdateCollectionRequestBody$Outbound;
};

/** @internal */
export const UpdateCollectionRequest$outboundSchema: z.ZodType<
  UpdateCollectionRequest$Outbound,
  z.ZodTypeDef,
  UpdateCollectionRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => UpdateCollectionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateCollectionRequestToJSON(
  updateCollectionRequest: UpdateCollectionRequest,
): string {
  return JSON.stringify(
    UpdateCollectionRequest$outboundSchema.parse(updateCollectionRequest),
  );
}

/** @internal */
export const UpdateCollectionResponse$inboundSchema: z.ZodType<
  UpdateCollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection: models.CollectionResponse$inboundSchema,
});

export function updateCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCollectionResponse' from JSON`,
  );
}
