/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpsertDocsRequestBody = {
  /**
   * A list of documents to upsert.
   */
  docs: Array<{ [k: string]: any }>;
};

export type UpsertDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpsertDocsRequestBody;
};

/** @internal */
export type UpsertDocsRequestBody$Outbound = {
  docs: Array<{ [k: string]: any }>;
};

/** @internal */
export const UpsertDocsRequestBody$outboundSchema: z.ZodType<
  UpsertDocsRequestBody$Outbound,
  z.ZodTypeDef,
  UpsertDocsRequestBody
> = z.object({
  docs: z.array(z.record(z.any())),
});

export function upsertDocsRequestBodyToJSON(
  upsertDocsRequestBody: UpsertDocsRequestBody,
): string {
  return JSON.stringify(
    UpsertDocsRequestBody$outboundSchema.parse(upsertDocsRequestBody),
  );
}

/** @internal */
export type UpsertDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: UpsertDocsRequestBody$Outbound;
};

/** @internal */
export const UpsertDocsRequest$outboundSchema: z.ZodType<
  UpsertDocsRequest$Outbound,
  z.ZodTypeDef,
  UpsertDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => UpsertDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function upsertDocsRequestToJSON(
  upsertDocsRequest: UpsertDocsRequest,
): string {
  return JSON.stringify(
    UpsertDocsRequest$outboundSchema.parse(upsertDocsRequest),
  );
}
