/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpsertDocsRequestBody = {
  /**
   * A list of documents to upsert.
   */
  docs: Array<{ [k: string]: any }>;
};

export type UpsertDocsRequest = {
  /**
   * Collection name.
   */
  collectionName: string;
  requestBody: UpsertDocsRequestBody;
};

/** @internal */
export const UpsertDocsRequestBody$inboundSchema: z.ZodType<
  UpsertDocsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  docs: z.array(z.record(z.any())),
});

/** @internal */
export type UpsertDocsRequestBody$Outbound = {
  docs: Array<{ [k: string]: any }>;
};

/** @internal */
export const UpsertDocsRequestBody$outboundSchema: z.ZodType<
  UpsertDocsRequestBody$Outbound,
  z.ZodTypeDef,
  UpsertDocsRequestBody
> = z.object({
  docs: z.array(z.record(z.any())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpsertDocsRequestBody$ {
  /** @deprecated use `UpsertDocsRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpsertDocsRequestBody$inboundSchema;
  /** @deprecated use `UpsertDocsRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpsertDocsRequestBody$outboundSchema;
  /** @deprecated use `UpsertDocsRequestBody$Outbound` instead. */
  export type Outbound = UpsertDocsRequestBody$Outbound;
}

export function upsertDocsRequestBodyToJSON(
  upsertDocsRequestBody: UpsertDocsRequestBody,
): string {
  return JSON.stringify(
    UpsertDocsRequestBody$outboundSchema.parse(upsertDocsRequestBody),
  );
}

export function upsertDocsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpsertDocsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpsertDocsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpsertDocsRequestBody' from JSON`,
  );
}

/** @internal */
export const UpsertDocsRequest$inboundSchema: z.ZodType<
  UpsertDocsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectionName: z.string(),
  RequestBody: z.lazy(() => UpsertDocsRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpsertDocsRequest$Outbound = {
  collectionName: string;
  RequestBody: UpsertDocsRequestBody$Outbound;
};

/** @internal */
export const UpsertDocsRequest$outboundSchema: z.ZodType<
  UpsertDocsRequest$Outbound,
  z.ZodTypeDef,
  UpsertDocsRequest
> = z.object({
  collectionName: z.string(),
  requestBody: z.lazy(() => UpsertDocsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpsertDocsRequest$ {
  /** @deprecated use `UpsertDocsRequest$inboundSchema` instead. */
  export const inboundSchema = UpsertDocsRequest$inboundSchema;
  /** @deprecated use `UpsertDocsRequest$outboundSchema` instead. */
  export const outboundSchema = UpsertDocsRequest$outboundSchema;
  /** @deprecated use `UpsertDocsRequest$Outbound` instead. */
  export type Outbound = UpsertDocsRequest$Outbound;
}

export function upsertDocsRequestToJSON(
  upsertDocsRequest: UpsertDocsRequest,
): string {
  return JSON.stringify(
    UpsertDocsRequest$outboundSchema.parse(upsertDocsRequest),
  );
}

export function upsertDocsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpsertDocsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpsertDocsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpsertDocsRequest' from JSON`,
  );
}
