/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { nullToUndefined, safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  IndexConfigsUnion,
  IndexConfigsUnion$inboundSchema,
} from "./indexconfigsunion.js";
import {
  PartitionConfig,
  PartitionConfig$inboundSchema,
} from "./partitionconfig.js";

export type CollectionResponse = {
  /**
   * Project name.
   */
  projectName: string;
  /**
   * Collection name.
   */
  collectionName: string;
  indexConfigs: { [k: string]: IndexConfigsUnion };
  /** Collection description. */
  description: string;
  /** Collection metadata tags. */
  tags: Record<string, string>;
  partitionConfig?: PartitionConfig | undefined;
  /**
   * Total number of partitions including the default partition.
   */
  numPartitions: number;
  /**
   * Total number of documents.
   */
  numDocs: number;
  /** Default writable Branch. */
  defaultBranchName: "main";
  /** Number of days that committed snapshots are retained. */
  snapshotRetentionInDays: number;
  /**
   * Collection creation time in milliseconds since the Unix epoch.
   */
  createdAt: number;
  /**
   * Collection last update time in milliseconds since the Unix epoch.
   */
  updatedAt: number;
  /**
   * Collection data last update time in milliseconds since the Unix epoch.
   */
  dataUpdatedAt?: number | undefined;
};

/** @internal */
export const CollectionResponse$inboundSchema: z.ZodType<
  CollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  indexConfigs: z.record(IndexConfigsUnion$inboundSchema),
  description: z.string(),
  tags: z.record(z.string()),
  partitionConfig: nullToUndefined(PartitionConfig$inboundSchema.optional()),
  numPartitions: z.number().int(),
  numDocs: z.number().int(),
  defaultBranchName: z.literal("main"),
  snapshotRetentionInDays: z.number().int().min(1).max(31),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  dataUpdatedAt: nullToUndefined(z.number().int().optional()),
});

export function collectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionResponse' from JSON`,
  );
}
