/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  IndexConfigsUnion,
  IndexConfigsUnion$inboundSchema,
} from "./indexconfigsunion.js";
import {
  PartitionConfig,
  PartitionConfig$inboundSchema,
} from "./partitionconfig.js";
import { Status, Status$inboundSchema } from "./status.js";

export type CollectionResponse = {
  /**
   * Project name.
   */
  projectName: string;
  /**
   * Collection name.
   */
  collectionName: string;
  indexConfigs: { [k: string]: IndexConfigsUnion };
  partitionConfig?: PartitionConfig | undefined;
  /**
   * Total number of partitions including the default partition.
   */
  numPartitions: number;
  /**
   * Total number of documents.
   */
  numDocs: number;
  /**
   * Source project name.
   */
  sourceProjectName?: string | undefined;
  /**
   * Source collection name.
   */
  sourceCollectionName?: string | undefined;
  /**
   * Source collection version.
   */
  sourceCollectionVersionId?: string | undefined;
  /**
   * Status
   */
  collectionStatus: Status;
  /**
   * Collection creation time in seconds since the Unix epoch.
   */
  createdAt: number;
  /**
   * Collection last update time in seconds since the Unix epoch.
   */
  updatedAt: number;
  /**
   * Collection data last update time in seconds since the Unix epoch.
   */
  dataUpdatedAt: number;
};

/** @internal */
export const CollectionResponse$inboundSchema: z.ZodType<
  CollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  collectionName: z.string(),
  indexConfigs: z.record(IndexConfigsUnion$inboundSchema),
  partitionConfig: PartitionConfig$inboundSchema.optional(),
  numPartitions: z.number().int(),
  numDocs: z.number().int(),
  sourceProjectName: z.string().optional(),
  sourceCollectionName: z.string().optional(),
  sourceCollectionVersionId: z.string().optional(),
  collectionStatus: Status$inboundSchema,
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  dataUpdatedAt: z.number().int(),
});

export function collectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionResponse' from JSON`,
  );
}
