/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type FieldsSelector2 = {
  /**
   * List of field names to include in the result.
   */
  include?: Array<string> | undefined;
  /**
   * List of field names to exclude in the result.
   */
  exclude: Array<string>;
};

export type FieldsSelector1 = {
  /**
   * List of field names to include in the result.
   */
  include: Array<string>;
  /**
   * List of field names to exclude in the result.
   */
  exclude?: Array<string> | undefined;
};

/**
 * An object to specify a list of field names to include and/or exclude in the result.
 */
export type FieldsSelectorUnion = FieldsSelector1 | FieldsSelector2;

/** @internal */
export type FieldsSelector2$Outbound = {
  include?: Array<string> | undefined;
  exclude: Array<string>;
};

/** @internal */
export const FieldsSelector2$outboundSchema: z.ZodType<
  FieldsSelector2$Outbound,
  z.ZodTypeDef,
  FieldsSelector2
> = z.object({
  include: z.array(z.string()).optional(),
  exclude: z.array(z.string()),
});

export function fieldsSelector2ToJSON(
  fieldsSelector2: FieldsSelector2,
): string {
  return JSON.stringify(FieldsSelector2$outboundSchema.parse(fieldsSelector2));
}

/** @internal */
export type FieldsSelector1$Outbound = {
  include: Array<string>;
  exclude?: Array<string> | undefined;
};

/** @internal */
export const FieldsSelector1$outboundSchema: z.ZodType<
  FieldsSelector1$Outbound,
  z.ZodTypeDef,
  FieldsSelector1
> = z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string()).optional(),
});

export function fieldsSelector1ToJSON(
  fieldsSelector1: FieldsSelector1,
): string {
  return JSON.stringify(FieldsSelector1$outboundSchema.parse(fieldsSelector1));
}

/** @internal */
export type FieldsSelectorUnion$Outbound =
  | FieldsSelector1$Outbound
  | FieldsSelector2$Outbound;

/** @internal */
export const FieldsSelectorUnion$outboundSchema: z.ZodType<
  FieldsSelectorUnion$Outbound,
  z.ZodTypeDef,
  FieldsSelectorUnion
> = z.union([
  z.lazy(() => FieldsSelector1$outboundSchema),
  z.lazy(() => FieldsSelector2$outboundSchema),
]);

export function fieldsSelectorUnionToJSON(
  fieldsSelectorUnion: FieldsSelectorUnion,
): string {
  return JSON.stringify(
    FieldsSelectorUnion$outboundSchema.parse(fieldsSelectorUnion),
  );
}
