/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { nullToUndefined, safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type IndexConfigsObject = {
  type: "object";
  objectIndexConfigs: { [k: string]: any };
};

export const TypeEnum = {
  Keyword: "keyword",
  Long: "long",
  Double: "double",
  Datetime: "datetime",
  Boolean: "boolean",
  SparseVector: "sparseVector",
} as const;
export type TypeEnum = ClosedEnum<typeof TypeEnum>;

/**
 * Types that do not need additional parameters.
 */
export type IndexConfigs = {
  type: TypeEnum;
};

/**
 * Vector similarity metric.
 */
export const Similarity = {
  Cosine: "cosine",
  Euclidean: "euclidean",
  DotProduct: "dot_product",
  MaxInnerProduct: "max_inner_product",
} as const;
/**
 * Vector similarity metric.
 */
export type Similarity = ClosedEnum<typeof Similarity>;

export type IndexConfigsVector = {
  type: "vector";
  /**
   * Set to false or omit for unmanaged vector fields.
   */
  managedEmbedding?: false | undefined;
  /**
   * Vector dimensions for unmanaged vector fields.
   */
  dimensions: number;
  /**
   * Vector similarity metric for unmanaged vector fields.
   */
  similarity?: Similarity | undefined;
};

export const EmbeddingProvider = {
  Openai: "openai",
} as const;
export type EmbeddingProvider = ClosedEnum<typeof EmbeddingProvider>;

/**
 * Managed embedding configuration for vector fields.
 */
export type EmbeddingConfig = {
  /**
   * Embedding provider.
   */
  provider: EmbeddingProvider;
  /**
   * Embedding model name. See /guides/collections/managed-embeddings for the current supported providers and models.
   */
  model: string;
  /**
   * Source text field name used to generate embeddings.
   */
  sourceField: string;
  /**
   * Embedding dimensions. Optional in requests and resolved in stored collection metadata.
   */
  dimensions?: number | undefined;
  /**
   * Vector similarity metric. Optional in requests and resolved in stored collection metadata.
   */
  similarity?: Similarity | undefined;
};

export type IndexConfigsManagedEmbeddingVector = {
  type: "vector";
  /**
   * Managed embedding vector field.
   */
  managedEmbedding: true;
  embedding: EmbeddingConfig;
};

export const Analyzer = {
  Standard: "standard",
  Korean: "korean",
  Japanese: "japanese",
  English: "english",
} as const;
export type Analyzer = ClosedEnum<typeof Analyzer>;

export type IndexConfigsText = {
  type: "text";
  /**
   * Analyzers.
   */
  analyzers?: Array<Analyzer> | undefined;
};

export type IndexConfigsUnion =
  | IndexConfigsText
  | IndexConfigsVector
  | IndexConfigsManagedEmbeddingVector
  | (IndexConfigs & { type: "keyword" })
  | (IndexConfigs & { type: "long" })
  | (IndexConfigs & { type: "double" })
  | (IndexConfigs & { type: "datetime" })
  | (IndexConfigs & { type: "boolean" })
  | (IndexConfigs & { type: "sparseVector" })
  | IndexConfigsObject;

/** @internal */
export const IndexConfigsObject$inboundSchema: z.ZodType<
  IndexConfigsObject,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("object"),
  objectIndexConfigs: z.record(z.any()),
});
/** @internal */
export type IndexConfigsObject$Outbound = {
  type: "object";
  objectIndexConfigs: { [k: string]: any };
};

/** @internal */
export const IndexConfigsObject$outboundSchema: z.ZodType<
  IndexConfigsObject$Outbound,
  z.ZodTypeDef,
  IndexConfigsObject
> = z.object({
  type: z.literal("object"),
  objectIndexConfigs: z.record(z.any()),
});

export function indexConfigsObjectToJSON(
  indexConfigsObject: IndexConfigsObject,
): string {
  return JSON.stringify(
    IndexConfigsObject$outboundSchema.parse(indexConfigsObject),
  );
}
export function indexConfigsObjectFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigsObject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndexConfigsObject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigsObject' from JSON`,
  );
}

/** @internal */
export const TypeEnum$inboundSchema: z.ZodNativeEnum<typeof TypeEnum> = z
  .nativeEnum(TypeEnum);
/** @internal */
export const TypeEnum$outboundSchema: z.ZodNativeEnum<typeof TypeEnum> =
  TypeEnum$inboundSchema;

/** @internal */
export const IndexConfigs$inboundSchema: z.ZodType<
  IndexConfigs,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: TypeEnum$inboundSchema,
});
/** @internal */
export type IndexConfigs$Outbound = {
  type: string;
};

/** @internal */
export const IndexConfigs$outboundSchema: z.ZodType<
  IndexConfigs$Outbound,
  z.ZodTypeDef,
  IndexConfigs
> = z.object({
  type: TypeEnum$outboundSchema,
});

export function indexConfigsToJSON(indexConfigs: IndexConfigs): string {
  return JSON.stringify(IndexConfigs$outboundSchema.parse(indexConfigs));
}
export function indexConfigsFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndexConfigs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigs' from JSON`,
  );
}

/** @internal */
export const Similarity$inboundSchema: z.ZodNativeEnum<typeof Similarity> = z
  .nativeEnum(Similarity);
/** @internal */
export const Similarity$outboundSchema: z.ZodNativeEnum<typeof Similarity> =
  Similarity$inboundSchema;

/** @internal */
export const IndexConfigsVector$inboundSchema: z.ZodType<
  IndexConfigsVector,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("vector"),
  managedEmbedding: nullToUndefined(z.literal(false).optional()),
  dimensions: z.number().int(),
  similarity: nullToUndefined(Similarity$inboundSchema.default("cosine")),
});
/** @internal */
export type IndexConfigsVector$Outbound = {
  type: "vector";
  managedEmbedding?: false | undefined;
  dimensions: number;
  similarity: string;
};

/** @internal */
export const IndexConfigsVector$outboundSchema: z.ZodType<
  IndexConfigsVector$Outbound,
  z.ZodTypeDef,
  IndexConfigsVector
> = z.object({
  type: z.literal("vector"),
  managedEmbedding: z.literal(false).optional(),
  dimensions: z.number().int(),
  similarity: Similarity$outboundSchema.default("cosine"),
}).strict();

export function indexConfigsVectorToJSON(
  indexConfigsVector: IndexConfigsVector,
): string {
  return JSON.stringify(
    IndexConfigsVector$outboundSchema.parse(indexConfigsVector),
  );
}
export function indexConfigsVectorFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigsVector, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndexConfigsVector$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigsVector' from JSON`,
  );
}

/** @internal */
export const EmbeddingProvider$inboundSchema: z.ZodNativeEnum<
  typeof EmbeddingProvider
> = z.nativeEnum(EmbeddingProvider);
/** @internal */
export const EmbeddingProvider$outboundSchema: z.ZodNativeEnum<
  typeof EmbeddingProvider
> = EmbeddingProvider$inboundSchema;

/** @internal */
export const EmbeddingConfig$inboundSchema: z.ZodType<
  EmbeddingConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  provider: EmbeddingProvider$inboundSchema,
  model: z.string(),
  sourceField: z.string(),
  dimensions: nullToUndefined(z.number().int().optional()),
  similarity: nullToUndefined(Similarity$inboundSchema.optional()),
});
/** @internal */
export type EmbeddingConfig$Outbound = {
  provider: string;
  model: string;
  sourceField: string;
  dimensions?: number | undefined;
  similarity?: string | undefined;
};

/** @internal */
export const EmbeddingConfig$outboundSchema: z.ZodType<
  EmbeddingConfig$Outbound,
  z.ZodTypeDef,
  EmbeddingConfig
> = z.object({
  provider: EmbeddingProvider$outboundSchema,
  model: z.string(),
  sourceField: z.string(),
  dimensions: z.number().int().optional(),
  similarity: Similarity$outboundSchema.optional(),
}).strict();

export function embeddingConfigToJSON(
  embeddingConfig: EmbeddingConfig,
): string {
  return JSON.stringify(EmbeddingConfig$outboundSchema.parse(embeddingConfig));
}
export function embeddingConfigFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingConfig' from JSON`,
  );
}

/** @internal */
export const IndexConfigsManagedEmbeddingVector$inboundSchema: z.ZodType<
  IndexConfigsManagedEmbeddingVector,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("vector"),
  managedEmbedding: z.literal(true),
  embedding: z.lazy(() => EmbeddingConfig$inboundSchema),
});
/** @internal */
export type IndexConfigsManagedEmbeddingVector$Outbound = {
  type: "vector";
  managedEmbedding: true;
  embedding: EmbeddingConfig$Outbound;
};

/** @internal */
export const IndexConfigsManagedEmbeddingVector$outboundSchema: z.ZodType<
  IndexConfigsManagedEmbeddingVector$Outbound,
  z.ZodTypeDef,
  IndexConfigsManagedEmbeddingVector
> = z.object({
  type: z.literal("vector"),
  managedEmbedding: z.literal(true),
  embedding: z.lazy(() => EmbeddingConfig$outboundSchema),
}).strict();

export function indexConfigsManagedEmbeddingVectorToJSON(
  indexConfigsManagedEmbeddingVector: IndexConfigsManagedEmbeddingVector,
): string {
  return JSON.stringify(
    IndexConfigsManagedEmbeddingVector$outboundSchema.parse(
      indexConfigsManagedEmbeddingVector,
    ),
  );
}
export function indexConfigsManagedEmbeddingVectorFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigsManagedEmbeddingVector, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IndexConfigsManagedEmbeddingVector$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigsManagedEmbeddingVector' from JSON`,
  );
}

/** @internal */
export const Analyzer$inboundSchema: z.ZodNativeEnum<typeof Analyzer> = z
  .nativeEnum(Analyzer);
/** @internal */
export const Analyzer$outboundSchema: z.ZodNativeEnum<typeof Analyzer> =
  Analyzer$inboundSchema;

/** @internal */
export const IndexConfigsText$inboundSchema: z.ZodType<
  IndexConfigsText,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("text"),
  analyzers: nullToUndefined(z.array(Analyzer$inboundSchema).optional()),
});
/** @internal */
export type IndexConfigsText$Outbound = {
  type: "text";
  analyzers?: Array<string> | undefined;
};

/** @internal */
export const IndexConfigsText$outboundSchema: z.ZodType<
  IndexConfigsText$Outbound,
  z.ZodTypeDef,
  IndexConfigsText
> = z.object({
  type: z.literal("text"),
  analyzers: z.array(Analyzer$outboundSchema).optional(),
});

export function indexConfigsTextToJSON(
  indexConfigsText: IndexConfigsText,
): string {
  return JSON.stringify(
    IndexConfigsText$outboundSchema.parse(indexConfigsText),
  );
}
export function indexConfigsTextFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigsText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndexConfigsText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigsText' from JSON`,
  );
}

/** @internal */
export const IndexConfigsUnion$inboundSchema: z.ZodType<
  IndexConfigsUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IndexConfigsText$inboundSchema),
  z.lazy(() => IndexConfigsVector$inboundSchema),
  z.lazy(() => IndexConfigsManagedEmbeddingVector$inboundSchema),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("keyword") }),
  ),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("long") }),
  ),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("double") }),
  ),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("datetime") }),
  ),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("boolean") }),
  ),
  z.lazy(() => IndexConfigs$inboundSchema).and(
    z.object({ type: z.literal("sparseVector") }),
  ),
  z.lazy(() => IndexConfigsObject$inboundSchema),
]);
/** @internal */
export type IndexConfigsUnion$Outbound =
  | IndexConfigsText$Outbound
  | IndexConfigsVector$Outbound
  | IndexConfigsManagedEmbeddingVector$Outbound
  | (IndexConfigs$Outbound & { type: "keyword" })
  | (IndexConfigs$Outbound & { type: "long" })
  | (IndexConfigs$Outbound & { type: "double" })
  | (IndexConfigs$Outbound & { type: "datetime" })
  | (IndexConfigs$Outbound & { type: "boolean" })
  | (IndexConfigs$Outbound & { type: "sparseVector" })
  | IndexConfigsObject$Outbound;

/** @internal */
export const IndexConfigsUnion$outboundSchema: z.ZodType<
  IndexConfigsUnion$Outbound,
  z.ZodTypeDef,
  IndexConfigsUnion
> = z.union([
  z.lazy(() => IndexConfigsText$outboundSchema),
  z.lazy(() => IndexConfigsVector$outboundSchema),
  z.lazy(() => IndexConfigsManagedEmbeddingVector$outboundSchema),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("keyword") }),
  ),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("long") }),
  ),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("double") }),
  ),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("datetime") }),
  ),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("boolean") }),
  ),
  z.lazy(() => IndexConfigs$outboundSchema).and(
    z.object({ type: z.literal("sparseVector") }),
  ),
  z.lazy(() => IndexConfigsObject$outboundSchema),
]);

export function indexConfigsUnionToJSON(
  indexConfigsUnion: IndexConfigsUnion,
): string {
  return JSON.stringify(
    IndexConfigsUnion$outboundSchema.parse(indexConfigsUnion),
  );
}
export function indexConfigsUnionFromJSON(
  jsonString: string,
): SafeParseResult<IndexConfigsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IndexConfigsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IndexConfigsUnion' from JSON`,
  );
}
