/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Partition field data type.
 */
export const DataType = {
  Keyword: "keyword",
} as const;
/**
 * Partition field data type.
 */
export type DataType = ClosedEnum<typeof DataType>;

export type PartitionConfig = {
  /**
   * Partition field name.
   */
  fieldName?: string | undefined;
  /**
   * Partition field data type.
   */
  dataType?: DataType | undefined;
  /**
   * The number of partitions.
   */
  numPartitions?: number | undefined;
};

/** @internal */
export const DataType$inboundSchema: z.ZodNativeEnum<typeof DataType> = z
  .nativeEnum(DataType);
/** @internal */
export const DataType$outboundSchema: z.ZodNativeEnum<typeof DataType> =
  DataType$inboundSchema;

/** @internal */
export const PartitionConfig$inboundSchema: z.ZodType<
  PartitionConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  fieldName: z.string().optional(),
  dataType: DataType$inboundSchema.optional(),
  numPartitions: z.number().int().optional(),
});
/** @internal */
export type PartitionConfig$Outbound = {
  fieldName?: string | undefined;
  dataType?: string | undefined;
  numPartitions?: number | undefined;
};

/** @internal */
export const PartitionConfig$outboundSchema: z.ZodType<
  PartitionConfig$Outbound,
  z.ZodTypeDef,
  PartitionConfig
> = z.object({
  fieldName: z.string().optional(),
  dataType: DataType$outboundSchema.optional(),
  numPartitions: z.number().int().optional(),
});

export function partitionConfigToJSON(
  partitionConfig: PartitionConfig,
): string {
  return JSON.stringify(PartitionConfig$outboundSchema.parse(partitionConfig));
}
export function partitionConfigFromJSON(
  jsonString: string,
): SafeParseResult<PartitionConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PartitionConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PartitionConfig' from JSON`,
  );
}
