/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PartitionFilter = {
  /**
   * Partition field name.
   */
  field: string;
  /**
   * Partition values to filter.
   */
  in: Array<string>;
};

/** @internal */
export type PartitionFilter$Outbound = {
  field: string;
  in: Array<string>;
};

/** @internal */
export const PartitionFilter$outboundSchema: z.ZodType<
  PartitionFilter$Outbound,
  z.ZodTypeDef,
  PartitionFilter
> = z.object({
  field: z.string(),
  in: z.array(z.string()),
});

export function partitionFilterToJSON(
  partitionFilter: PartitionFilter,
): string {
  return JSON.stringify(PartitionFilter$outboundSchema.parse(partitionFilter));
}
