/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  projectApiKey?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  ProjectApiKey?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  projectApiKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    projectApiKey: "ProjectApiKey",
  });
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
