/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Status
 */
export const Status = {
  Creating: "CREATING",
  Active: "ACTIVE",
  Deleting: "DELETING",
} as const;
/**
 * Status
 */
export type Status = ClosedEnum<typeof Status>;

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);
