/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export * from "./lib/config.js";
export * as files from "./lib/files.js";
export { HTTPClient } from "./lib/http.js";
export type { Fetcher, HTTPClientOptions } from "./lib/http.js";
export * from "./sdk/sdk.js";

/** Collection-scoped client (recommended). See docs/REFACTORING_STATUS.md */
export {
  LambdaDBClient,
  CollectionHandle,
  DEFAULT_BASE_URL,
  DEFAULT_PROJECT_NAME,
  type RequestOptions as ClientRequestOptions,
  type LambdaDBClientOptions,
} from "./client.js";

/** Public API types (inputs and responses for the collection-scoped client). */
export type * from "./types/public.js";

/**
 * @deprecated Use types from the package root (e.g. CreateCollectionInput, QueryCollectionResponse). Will be removed in the next major version.
 */
export type { operations, models } from "./client.js";
